version: '3.8'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    depends_on:
      - postgres



  postgres:
    image: 'postgres:16.1'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=eurofarma
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
    depends_on:
      - postgres